import numpy as np

language = {'pt':['Bom dia', 'Boa tarde', 'Boa noite', 'Pesquisar', 'Início', 'Entrar', 'Cadastrar', 'Biblioteca', 'Crie sua primeira Playlist', 'É fácil, deixa eu te ajudar', 'Adicionar Playlist', 'Cookies', 'Navegar por todas as seções', 'Boas Festas', 'Feitos para você', 'Lançamentos', 'Creatos', 'Para treinar', 'Podcasts', 'Sertanejo', 'Samba e pagode', 'Funk', 'MPB', 'Rock', 'Hip Hop', 'Indie', 'Relax', 'Música Latina', 'Teste o Spotify Premium de graça', 'Inscreva-se para curtir músicas e podcasts de forma ilimitada e sem anúncios.', 'Inscreva-se', 'Artista', 'selected'],
'en':['Good morning', 'Good afternoon', 'Good night', 'Search', 'Home', 'Log In', 'Log On', 'Library', 'Create your first Playlist', 'It\'s easy, let me help you.', 'Add Playlist', 'Cookies', 'Browse all sections', 'Good Parties', 'Made for you', 'Releases', 'Creators', 'For gym', 'Podcasts', 'Country', 'Brazilian Samba and Pagode', 'Brazilian Funk', 'MPB', 'Rock', 'Hip Hop', 'Indie', 'Relax', 'Latino music', 'Test Spotify Premium now for free', 'Subscribe to enjoy musics and podcasts in a unlimited way and no ads.', 'Subscribe', 'Artist', '', 'selected'],
'es':['Buenos días', 'Buenas tardes', 'Buenas noches', 'Buscar', 'Inicio', 'Iniciar sesión', 'Registrarse', 'Biblioteca', 'Crea tu primera lista de reproducción', 'Es fácil, déjame ayudarte', 'Agregar lista de reproducción', 'Cookies', 'Navegar por todas las secciones', 'Felices fiestas', 'Hecho para ti', 'Lanzamientos', 'Creadores', 'Para entrenar', 'Podcasts', 'Country', 'Samba y pagode brasileño', 'Funk brasileño', 'MPB', 'Rock', 'Hip Hop', 'Indie', 'Relax', 'Música latina', 'Prueba Spotify Premium gratis', 'Suscríbete para disfrutar de música y podcasts de manera ilimitada y sin anuncios.', 'Suscríbete', 'Artista', '', '', 'selected'],
'it':['Buongiorno', 'Buon pomeriggio', 'Buona notte', 'Ricerca', 'Home', 'Accedi', 'Iscriviti', 'Libreria', 'Crea la tua prima playlist', 'È facile, lascia che ti aiuti', 'Aggiungi playlist', 'Cookies', 'Sfoglia tutte le sezioni', 'Buone Feste', 'Fatto per te', 'Novità', 'Creatori', 'Per l\'allenamento', 'Podcast', 'Country', 'Samba brasiliano', 'Funk brasiliano', 'MPB', 'Rock', 'Hip Hop', 'Indie', 'Rilassati', 'Musica latina', 'Prova Spotify Premium gratuitamente', 'Iscriviti per goderti musica e podcast in modo illimitato e senza pubblicità.', 'Iscriviti', 'Artista', '', '', '', 'selected'],
'fr':['Bonjour', 'Bon après-midi', 'Bonne nuit', 'Recherche', 'Accueil', 'Se connecter', 'S\'inscrire', 'Bibliothèque', 'Créez votre première playlist', 'C\'est facile, laissez-moi vous aider', 'Ajouter une playlist', 'Cookies', 'Parcourir toutes les sections', 'Joyeuses fêtes', 'Fait pour vous', 'Nouveautés', 'Créateurs', 'Pour l\'entraînement', 'Podcasts', 'Country', 'Samba brésilien', 'Funk brésilien', 'MPB', 'Rock', 'Hip Hop', 'Indie', 'Détendez-vous', 'Musique latine', 'Testez Spotify Premium gratuitement', 'Abonnez-vous pour profiter de la musique et des podcasts de manière illimitée et sans publicité.', 'Abonnez-vous', 'Artiste', '', '', '', '', 'selected'],
'de':['Guten Morgen', 'Guten Tag', 'Gute Nacht', 'Suche', 'Zuhause', 'Anmelden', 'Einloggen', 'Bibliothek', 'Erstelle deine erste Playlist', 'Es ist einfach, lass mich dir helfen', 'Playlist hinzufügen', 'Cookies', 'Alle Abschnitte durchsuchen', 'Frohe Feiertage', 'Für dich gemacht', 'Neuerscheinungen', 'Schöpfer', 'Für das Training', 'Podcasts', 'Country', 'Brasilianischer Samba', 'Brasilianischer Funk', 'MPB', 'Rock', 'Hip Hop', 'Indie', 'Entspannen', 'Lateinamerikanische Musik', 'Teste Spotify Premium jetzt kostenlos', 'Abonnieren, um Musik und Podcasts unbegrenzt und ohne Werbung zu genießen.', 'Abonnieren', 'Künstler', '', '', '', '', '', 'selected'],
'ru':['Доброе утро', 'Добрый день', 'Доброй ночи', 'Поиск', 'Главная', 'Войти', 'Войти', 'Библиотека', 'Создайте свой первый плейлист', 'Это легко, позвольте мне вам помочь', 'Добавить плейлист', 'Cookies', 'Просмотреть все разделы', 'С новым годом', 'Сделано для вас', 'Новинки', 'Творцы', 'Для тренировок', 'Подкасты', 'Кантри', 'Бразильский самба', 'Бразильский фанк', 'MPB', 'Рок', 'Хип-хоп', 'Инди', 'Расслабьтесь', 'Латиноамериканская музыка', 'Попробуйте Spotify Premium бесплатно', 'Подпишитесь, чтобы наслаждаться музыкой и подкастами неограниченно и без рекламы.', 'Подписаться', 'Артист', '', '', '', '', '', '', 'selected'],
'zh':['早上好', '下午好', '晚上好', '搜索', '主页', '登录', '注册', '图书馆', '创建您的第一个播放列表', '很容易，让我来帮你', '添加播放列表', 'Cookies', '浏览所有部分', '新年好', '为您制作', '新发布', '创作者', '用于健身', '播客', 'Country', '巴西桑巴', '巴西放克', 'MPB', '摇滚', '嘻哈', '独立', '放松', '拉丁音乐', '免费试用 Spotify Premium', '订阅以无限制且无广告地享受音乐和播客。', '订阅', '艺术家', '', '', '', '', '', '', '', 'selected'],
'ja':['おはようございます', 'こんにちは', 'こんばんは', '検索', 'ホーム', 'ログイン', 'サインアップ', 'ライブラリ', '最初のプレイリストを作成', '簡単です、手伝わせてください', 'プレイリストに追加', 'Cookies', 'すべてのセクションを閲覧', '良いパーティー', 'あなたのために作られました', 'リリース', 'クリエイター', 'トレーニング用', 'ポッドキャスト', 'Country', 'ブラジリアン・サンバ', 'ブラジリアン・ファンク', 'MPB', 'ロック', 'ヒップホップ', 'インディ', 'リラックス', 'ラテン音楽', 'Spotify Premiumを無料で試す', '無制限かつ広告なしで音楽とポッドキャストを楽しむには購読してください。', '購読', 'アーティスト', '', '', '', '', '', '', '', '', 'selected'],
'ko':['안녕하세요', '안녕하세요', '안녕히 주무세요', '검색', '홈', '로그인', '가입', '도서관', '첫 번째 재생 목록 만들기', '쉬워요, 도와드릴게요', '재생 목록에 추가', 'Cookies', '모든 섹션 둘러보기', '즐거운 연휴', '당신을 위해 만들어졌어요', '최신곡', '크리에이터', '운동을 위해', '팟 캐스트', 'Country', '브라질 삼바', '브라질 펑크', 'MPB', '락', '힙합', '인디', '휴식', '라틴 음악', 'Spotify 프리미엄을 무료로 체험해보세요', '광고 없이 무제한으로 음악 및 팟 캐스트를 즐기려면 가입하세요.', '가입하기', '아티스트', '', '', '', '', '', '', '', '', '', 'selected']}

